version: "3"

services:
  lobby_service:
    build: ./lobby_service
    ports:
      - "5000:5000"

  blizzard_bounce:
    build: ./gameservices/blizzard_bounce
    ports:
      - "8001:8001"

  trivia:
    build: ./gameservices/trivia
    ports:
      - "8002:8002"

  type_race:
    build: ./gameservices/type_race
    ports:
      - "8003:8003"
